# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "pwd command:"
          pwd
          echo "Who is the user?"
          whoami
          echo "Knowing the content of the directory:"
          ls -la
          echo "Create or not a directory:"
          mkdir -p project
          echo "cd into de project directory:"
          cd project/
          echo "echo -e command:"
          echo -e "Today is $(date) \nAdd other actions to build, test, and deploy your project." >> output.txt
          echo "pwd command:"
          pwd
          echo "cat output.txt command:"
          cat output.txt
          echo "ls -al command:"
          ls -al
          echo "cat /etc/*release command:"
          cat /etc/*release
          echo -e "The Calendar is $(cal)\nToday is $(date) \nAdd other actions to build, test, and deploy your project." >> output.txt
          cat output.txt
